In [1]:
import numpy as np 

In [2]:
print(np.__version__)

2.5.1


In [ ]:
a = np.array([1,2,3,4,5]) # 1D array

In [4]:
a

array([1, 2, 3, 4, 5])

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) #for matrix 

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # for representing 3D matrix 

In [9]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### built-in creators

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [17]:
np.arange(0,10,2) # (start,stop,step)

array([0, 2, 4, 6, 8])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.linspace(0,1,5) # 5 evenly spaced 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
np.random.rand(3,3)

array([[0.58992177, 0.89363042, 0.3306207 ],
       [0.4287493 , 0.87275333, 0.83819388],
       [0.74743034, 0.68991724, 0.63319606]])

In [25]:
np.random.rand(3)

array([0.83465937, 0.95282471, 0.61683261])

In [26]:
np.random.randint(1,10,(2,4))

array([[3, 3, 5, 9],
       [3, 8, 5, 1]])

### Attributes


In [28]:
a = np.array([[1,2,3],[4,5,6]])

In [34]:
print(a.shape) # Dimensions as tuple

(2, 3)


In [35]:
print(a.ndim) # Number of dimensions


2


In [36]:
print(a.size) # total number of elements

6


In [37]:
print(a.dtype) # data type of element 

int64


In [38]:
print(a.itemsize) # bytes per element 

8
